In [60]:
import numpy as np

In [61]:
# QR iteration --- Make students write this
def qr_iterate(a, n):
    a1 = a.copy()
    for _ in range(n):
        q, r = np.linalg.qr(a1)
        a1 = r @ q
    return a1

# 1. QR iteration for a symmetric matrix

In [71]:
# construct a symmetric PD matrix

rndm = np.random.RandomState(1)
a = np.random.uniform(size=(5, 5))
A = a.T @ a
A

array([[1.92435435, 1.36919224, 1.16623152, 1.84975439, 1.62284295],
       [1.36919224, 1.30357433, 0.96824262, 1.45354805, 1.06331529],
       [1.16623152, 0.96824262, 0.92462551, 1.16481407, 1.16852012],
       [1.84975439, 1.45354805, 1.16481407, 2.07789842, 1.63594202],
       [1.62284295, 1.06331529, 1.16852012, 1.63594202, 1.80418509]])

In [72]:
np.linalg.eigvals(A)

array([7.15900171, 0.49077375, 0.23828686, 0.14173221, 0.00484317])

In [73]:
# do the QR iteration, vary the number of steps, check the form of the result

A1 = qr_iterate(A, 50)
np.set_printoptions(suppress=True, linewidth=100)
A1

array([[ 7.15900171,  0.        , -0.        ,  0.        ,  0.        ],
       [-0.        ,  0.49077375,  0.        ,  0.        , -0.        ],
       [ 0.        , -0.        ,  0.23828686, -0.        , -0.        ],
       [ 0.        , -0.        , -0.        ,  0.14173221, -0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ,  0.00484317]])

In [74]:
# 1. Compare the diagonal of A1 with eigenvalues of A
np.diag(A1)

array([7.15900171, 0.49077375, 0.23828686, 0.14173221, 0.00484317])

In [75]:
# study the convergence of the diag elements with the number of iterations

eigv = np.linalg.eigvals(A)
qr_eigv = np.diag(A1)

np.sort(eigv) - np.sort(qr_eigv)

array([ 0.,  0., -0.,  0., -0.])

In [76]:
# 2. study the convergence of elements below the main diagonal

# 2. QR iteration for a general (not symmetric matrix)

In [77]:
# Take the original matrix A, do the QR iteration

In [78]:
# vary the number of steps, start with ten or so ; note that it converges to a *real* Schur form, with 2x2 blocks

a1 = qr_iterate(a, 1500)
a1

array([[ 2.4994449 ,  0.42126114, -0.76746605, -0.27587524, -0.15824606],
       [ 0.        , -0.58230225,  0.27943303, -0.10750288,  0.25733558],
       [ 0.        , -0.2281125 , -0.40765121, -0.14037079,  0.01697414],
       [ 0.        ,  0.        , -0.        ,  0.42514572, -0.01711343],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.07491993]])

In [79]:
# check the eigenvalues: note the complex conjugate pairs; 
# note that the real ones agree with the diagonal of the results of the QR iteration
np.linalg.eigvals(a)

array([ 2.4994449 +0.j        , -0.49497673+0.23688905j, -0.49497673-0.23688905j,
        0.42514572+0.j        ,  0.07491993+0.j        ])

In [80]:
# Note a 2x2 block, check its eigenvalues
block = a1[1:3, 1:4]
block

array([[-0.40765121, -0.14037079],
       [-0.        ,  0.42514572]])

In [81]:
# Eigenvalues of the block agree with complex conj eigvals of A
np.linalg.eigvals(block)

array([-0.40765121,  0.42514572])

# 3. Classwork

Each student gets their own random seed: make it e.g. equal to their student ID number

repeat the analysis, select 2x2 blocks, compare to the "ground truth" eigenvalues